#!/usr/bin/env python3
"""Generate src/mkdata.txt: a TI-BASIC program that stores element data as
one list per field, taken from the Disp strings of the element programs.

    python3 tools/build-mkdata.py 5        # atomic numbers 1-5
    python3 tools/ti89-pack.py src/mkdata.txt periodic.mkdata.89p

Item n of every list is element n, so only a contiguous range starting at
Hydrogen is supported.
"""
import glob
import re
import sys

import ti89charset

# (screen, list variable, label pattern). The label is stripped and only the
# value is stored; periodic\table supplies the label when displaying.
FIELDS = [
    (1, "elnm",   r"Name:"),
    (1, None,     r"Symbol:"),          # split into elsym and elgrp below
    (1, None,     r"Atomic Number:"),   # the list index itself
    (1, "elwt",   r"Atomic (?:Weight|Mass):"),
    (1, "eltype", r"Type:"),
    (1, "elcfg",  r""),                 # electron configuration, no label
    (2, "elbp",   r"Boiling Point,? ?\(K\)="),
    (2, "elmp",   r"Melting Point,? ?\(K\)="),
    (2, "elox",   r"Oxydation St(?:ates|ts) *="),
    (2, "eldens", r"Density="),
    (2, "elsom",  r"SoM="),
    (3, "elcrad", r"Covalent Radius,[Aa]="),
    (3, "elarad", r"Atomic +Radius,A="),
    (3, "elavol", r"Atomic +Volume *="),
    (3, "elfipv", r"FIPV="),
    (3, "elshc",  r"SHC *="),
    (3, "elcs",   r"CS="),
    (4, "elen",   r"EN *= ?"),
    (4, "elhov",  r"HoV="),
    (4, "elhof",  r"HoF="),
    (4, "elec",   r"EC *="),
    (4, "eltc",   r"TC *="),
    (4, "elabp",  r"ABP="),
]

NOT_ELEMENTS = {"periodic", "atomnum", "template", "table", "mkdata"}

LISTS = ["elnm", "elsym", "elgrp"] + [v for _, v, _ in FIELDS if v and v != "elnm"]


def program_text(path):
    d = open(path, "rb").read()
    n = int.from_bytes(d[0x56:0x58], "big")
    body = d[0x58:0x58 + n]
    if body[-2] != 0x08:
        return None  # tokenized; no source text
    return ti89charset.decode(body.split(b"\0", 1)[0])


def parse(path, text):
    screens = [re.findall(r'"([^"]*)"', l) for l in text.split("\n")
               if l.startswith("Disp ")][:4]
    rec, num = {}, None
    for screen, var, label in FIELDS:
        strings = screens[screen - 1]
        if var == "elcfg":
            rec[var] = strings[5]
            continue
        hits = [s for s in strings if re.match(label, s)]
        if len(hits) != 1:
            sys.exit("%s: expected one %r on screen %d, found %r"
                     % (path, label, screen, strings))
        value = re.sub("^" + label, "", hits[0]).strip()
        if label == "Symbol:":
            m = re.match(r"(\S+)\s*-\s*(.*)$", value)
            if not m:
                sys.exit("%s: cannot split symbol and group in %r" % (path, value))
            rec["elsym"], rec["elgrp"] = m.group(1), m.group(2).strip()
        elif label == "Atomic Number:":
            num = int(value)
        else:
            rec[var] = value
    return num, rec


def ti_list(items):
    return "{" + ",".join(items) + "}"


def ti_str(s):
    if '"' in s:
        sys.exit("string contains a quote: %r" % s)
    return '"%s"' % s


def main(count):
    by_num = {}
    for path in glob.glob("periodic.*.89p"):
        if path.split(".")[1] in NOT_ELEMENTS:
            continue
        text = program_text(path)
        m = re.search(r'"Atomic Number:(\d+)"', text or "")
        if m and int(m.group(1)) <= count:
            num, rec = parse(path, text)
            by_num[num] = rec
    missing = [n for n in range(1, count + 1) if n not in by_num]
    if missing:
        sys.exit("no text-stored element program for atomic numbers %s" % missing)
    recs = [by_num[n] for n in range(1, count + 1)]

    byname = sorted(range(1, count + 1), key=lambda n: recs[n - 1]["elnm"])
    bysym = sorted(range(1, count + 1), key=lambda n: recs[n - 1]["elsym"])

    out = ["()", "Prgm",
           "© Generated by tools/build-mkdata.py. Do not edit by hand.",
           "© Item n of each list is the element with atomic number n",
           "© (1-%d)." % count]
    for var in LISTS:
        out.append(ti_list(ti_str(r[var]) for r in recs) + "→periodic\\" + var)
    out.append("© Atomic numbers sorted by name, and by symbol")
    out.append(ti_list(str(n) for n in byname) + "→periodic\\byname")
    out.append(ti_list(str(n) for n in bysym) + "→periodic\\bysym")
    out += ["ClrIO", 'Disp "Data stored for %d","elements. Now run","periodic\\table()"' % count,
            "EndPrgm"]
    open("src/mkdata.txt", "w", encoding="utf-8").write("\n".join(out) + "\n")


if __name__ == "__main__":
    main(int(sys.argv[1]) if len(sys.argv) > 1 else 5)
